apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs-node-service
  name: ipfs-node
spec:
  ports:
    - name: p2p
      port: 4001
      targetPort: 4001
  selector:
    app: ipfs-node-pod
  type: LoadBalancer
