apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs-node-service
  name: ipfs-node
spec:
  ports:
    - name: gateway
      port: 8080
      targetPort: 8080
    - name: rpc
      port: 5001
      targetPort: 5001
  selector:
    app: ipfs-node-pod
  type: Service
