apiVersion: v1
kind: Service
metadata:
  labels:
    app: charlie-ipfs-node-service-service
  name: charlie-ipfs-node-service
spec:
  ports:
    - name: p2p
      port: 4001
      targetPort: 4001
  selector:
    app: charlie-ipfs-node-service-pod
  type: ExternalName
