apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs-node-bravo-service
  name: ipfs-node-bravo
spec:
  ports:
    - name: p2p
      port: 4001
      targetPort: 4001
  selector:
    app: ipfs-node-bravo-pod
  type: ExternalName
