apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs-node-alpha-service
  name: ipfs-node-alpha
spec:
  ports:
    - name: p2p
      port: 4001
      targetPort: 4001
  selector:
    app: ipfs-node-alpha-pod
  type: ExternalName
