
import { SERVICE_DEFAULT } from "./service";
import { INGRESS_DEFAULT } from "./ingress";
import { CONFIGMAP_DEFAULT } from "./configmap";
import { DEPLOYMENT_DEFAULT } from "./deployment";
import { STATEFULLSET_DEFAULT } from "./statefullset";

export const DEFAULTS: any = {}
DEFAULTS.SERVICE = SERVICE_DEFAULT
DEFAULTS.INGRESS = INGRESS_DEFAULT
DEFAULTS.CONFIGMAP =  CONFIGMAP_DEFAULT
DEFAULTS.DEPLOYMENT = DEPLOYMENT_DEFAULT
DEFAULTS.STATEFULLSET  = STATEFULLSET_DEFAULT


